server:
  port: 8082
  servlet:
    context-path: /work

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017
      authentication-database: admin
      username: Aroad
      password: 123456
      host: 127.0.0.1
      port: 27017
      database: smw1
      uri: mongodb://localhost/smw1
